version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - springboot-net

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8084:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: mvn spring-boot:run
    networks:
      - springboot-net

volumes:
  db_data:

networks:
  springboot-net:
